### ISSUE TITLE
Does this repository has a roadmap?

### ISSUE THREAD

**Issue by firminochangani** [mchandleraz/realworld-vue#6]
I am new with Vue but I want to contribute and I kind of lost. Is any roadmap available? If not, what do you think of using a public board on Trello or Github task list to do so?

**Comment by mchandleraz** [comment]
Hey @flowck,

I'm new to Vue as well so hopefully we can both learn from this project. As far as contributing, the folks from Thinkster have put together some info on that. Here's some stuff to get you started:
https://github.com/gothinkster/realworld

As far as contributing to this repo specifically: If you see something that you can do to get us closer to the RealWorld spec, submit a PR. I'd really like to have unit tests where appropriate, so if you're not familiar with writing tests I can work with you on that.

Let me know if you need any help or more info on getting started.

-Matt

**Comment by sinchang** [comment]
I am confused, why use bootstrap-vue? after `npm run dev`, page layout confusion.

![](https://ooo.0o0.ooo/2017/05/15/591950e6bef35.png)

**Comment by firminochangani** [comment]
Hi @mchandleraz, 

I do want to contribute but I am not familiar with testing code, but yeah I can try.

**Comment by firminochangani** [comment]
@sinchang I am seeing that too.

**Comment by sinchang** [comment]
I think we should remove bootstrap-vue. cc @mchandleraz

**Comment by mchandleraz** [comment]
Hey guys, I'm wrapping up some client work this week and should be able to focus more on this next week. I'll take a look at this issue tonight, though. Thanks for your patience!

**Comment by vilsbole** [comment]
@sinchang removing bootstrap-vue from the project, fixes the header styles and the footer colors.
#15 implements the required changes.
Since I'm not using yarn I wasn't able to update the lock file, by I would be glad to install if needed.

**Comment by vilsbole** [comment]
@sinchang for the tags displaying inline, we just need to update the styles #16.

**Comment by mchandleraz** [comment]
I'm gonna close this, since it's diverged from its original topic. Feel free to open a new issue if any of this needs more discussion.
